apiVersion: v1
kind: Pod
metadata:
    name: pod-webapp-red
    namespace: production
    labels:
        app: web
spec:
    containers:
        - name: webapp-red
          image: kodekloud/webapp-color
          ports:
            - containerPort: 8080
          env:
            - name: APP_COLOR
              value: red